### ISSUE TITLE
Request: number raid wing doors

### ISSUE THREAD

**Issue by SaladFork** [QuitarHero/Heros-Marker-Pack#70]
It would be helpful if this addon could number the wing doors in the world and on the minimap in Lion's Arch Aerodrome. For example, the door/portal to Spirit Vale could be labeled with a "1" as it is commonly referred to as "Wing 1". I believe this could reuse the number textures (e.g. [1.png](https://github.com/QuitarHero/Heros-Marker-Pack/blob/master/Blish%20HUD/Data/General/1.png)) that already exist in this pack.

**Comment by QuitarHero** [comment]
Hey,

I agree it is a great idea. I already have it implemented in my dev/testing "marker pack," shown here:
https://imgur.com/a/7LesMJi

I would like to implement both a text variant and a numerical variant to each raid wing's entrance, but currently Blish HUD does not support hiding categories by default (which is why, for example, you see KC's "rift" markers by default, and why I removed all of Slothasor's mushroom paths, among other features), so providing flexible options to the end-user isn't something I can do for the time being.

I may play around with a hybrid of resizing the text on the entrances so they're easier to see, then have numbers shown on the minimap, though I do understand that numbers are much easier to see and identify at a glance.
I'll think of a compromise and throw a solution in the next release.

Thanks :)
