### ISSUE TITLE
Adding an indicator in Temple of Febe strike mission that shows Rage circle radius

### ISSUE THREAD

**Issue by vixelina** [QuitarHero/Heros-Marker-Pack#75]
The boss isn't centered on the arena so the rage circle also isn't centered. On CM I feel it'd be useful for people to know where exactly the rage radius (empowered and/or not empowered) ends before the mechanic actually appears.

**Comment by QuitarHero** [comment]
Thanks for the suggestion.

The issue isn't whether the feature would be helpful or not, but how it'd be perceived mid-fight with how hard the DPS check is for some groups (such as my own normal CM group and how our group DPS makes it equivalent to LCM).

AoE's in Guild Wars 2 like to shrink when there's also an inner-AoE associated with it. Generally speaking, it's not really relevant because most AoE's are small, and we shouldn't need to think about it. And as far as I know, the "hitbox" of the AoE when it fully shrinks, *not* the starting size.

This becomes more relevant with larger AoE's, such as HT's Primordus Chomp and Cerus's Rage. So as I expect you're aware of, when a Scourge Portal is placed on the edge of Cerus's Rage, it can be hard to know if it needs to be taken early or not, and if it needs to be called to the group in voice. And that can be a lot of DPS downtime if it needs to be taken early if, for example, the portal is *actually* safe, just on the border of what's acceptable (given the hard-to-see nature of Scourge Portals).

The issues I perceive are thus:
- I could make a Rage circle marker that's slightly larger than the actual size of Cerus's Rage (this is just for Empowered Rage; for normal rage just being in melee range is enough to Scourge Portal out, unless it's really needed in a non-scourge group). The issue here is if it's closer than that AoE, it can confuse players and callouts, and now they're looking at 2 separate AoE borders instead of 1.
- I can make a Rage circle marker that's the actual size of the AoE, but that can make more incorrect callouts in voice, which results in either more DPS downtime, or Cerus gaining a lot of Empowered Stacks.

In my mind, both scenarios cause real issues that can backfire on the group, which is why I haven't implemented this yet. Perhaps I'm wrong and it wouldn't be an issue at all. But the further a group gets into a fight, if there are markers and trails provided, they'll be *relied* on more and more and not so much used as a simple aide for callouts and rage portal placements. And thus far I haven't thought of a good solution for it.

On a related note, I've made a Febe Simulation a few months ago (here's a [video showcase](https://youtu.be/aNEHjSSEOpM) of an early draft of Phase 3 with my custom strategy), so I'm aware of how useful this information could be.

I'd be interested in hearing your thoughts on the issue, as I would like to maintain accuracy with these markers, but due to the nature of the fight (and the fact that we can't just casually walk around the arena like we can in Harvest Temple), I'd rather not create a feature that can cause even more issues than the lack of it already does.

**Comment by QuitarHero** [comment]
With no response I'll be closing this issue.
